name: CI Tests

on: [push, pull_request]

jobs:
  ci_tests:
    name: python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.14.0-rc.2
        uses: actions/setup-python@v5
        with:
          python-version: 3.14.0-rc.2

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Lint
        run: uv run ruff check

      - name: Check formatting
        run: uv run ruff format --check

      - name: Type check with Pyright
        run: uv run pyright

      - name: Type check with Ty
        run: uv run ty check

      - name: Run tests
        run: uv run pytest -v
